### PR TITLE
CORS (rev1)

### PR DESCRIPTION
**Pull request by coryasilva**
@oarevalo This is working in our simple production environment and everything works.  Though, please review the code as I am a coldfusion noob.

This is in response to pull request #128, but with proper branching

### CODE REVIEW

**Comment by oarevalo** [comment]
Looks pretty good, the only change I think would make sense is to move the value of `Access-Control-Max-Age` to the config. Seems a bit of a "magic number" to just include it directly on the template. Also would make it for easier customization.

**Comment by coryasilva** [comment]
Yeah I was thinking about moving all of the header values to the settings but was trying not to pollute the settings and/or overwhelm the users.  Then again if you are tracking bugs you are probably a developer or IT guy...  

What do you think all settings or just add maxAge

**Comment by oarevalo** [comment]
I had the same thought (re: too many settings). 
But there is a trick that can allow conciseness and also extensibility. 
The `getSetting()` method takes a second argument for a default value, so that if the requested setting is not found on the Config file, it returns that value.

That way you can do something like:
```
var cors.allowCredentials = service.getConfig().getSetting("cors.allowCredentials", false);
```
without having to necessarily add more stuff to the config. The only important bit would be to add some documentation somewhere indicating the additional/optional config settings that can be used to configure CORS. I think just a brief comment on the listener cfm indicating the names of the used settings should be enough.

**Comment by coryasilva** [comment]
Okay that makes sense; I think that should do it.

**Comment by oarevalo** [comment]
Merged to the 1.8 branch. Will be merged into master shortly.

**Comment by coryasilva** [comment]
Awesome.  Thanks.

**Pull request merged**
